 platform :ios, '9.0'
 use_frameworks!

target 'Nearsoft' do

  pod 'Google/SignIn'
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireImage', '~> 2.0'
  pod 'ObjectMapper', '~> 1.3'
  pod 'RealmSwift'

end
